[workspace]
members = [
    "node",
    "pallets/subtensor",
    "pallets/commitments",
    "runtime",
    "pallets/registry"
]
resolver = "2"

[workspace.package]
version = "4.0.0-dev"
authors = ["Bittensor Nucleus Team"]
description = "A short description of my package"
documentation = "https://bittensor.com"
edition = "2021"

[profile.release]
panic = "unwind"

[profile.test]
opt-level = 3
