[workspace]
members = [
    "integration-tests",
    "node",
    "pallets/subtensor",
    "runtime",
]

[profile.ci-dev]
inherits = "dev"
opt-level = 0
incremental = true
codegen-units = 256

[profile.ci-test]
inherits = "ci-dev"

[profile.ci-release]
inherits = "release"
panic = "unwind"
opt-level = 3
codegen-units = 8
