[workspace]
members = [
    "integration-tests",
    "node",
    "pallets/subtensor",
    "runtime",
]

[profile.dev]
opt-level = 1
codegen-units = 16
incremental = true

[profile.test]
inherits = "dev"
opt-level = 1
codegen-units = 16
incremental = true

[profile.release]
panic = "unwind"
opt-level = 3
codegen-units = 8
